name: Build Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@decahedra'
          always-auth: true
      - name: install deps, build and postbuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm install
          pnpm prepublishOnly
          npx semantic-release
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
